#dom20 ( Postgres )

version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: dom20
      POSTGRES_PASSWORD: postgress_password
      POSTGRES_DB: database_postgress
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
